```yaml
openapi: 3.0.0
info:
  title: DocuCraft AI API
  version: 1.0.0
paths:
  /document/retrieve:
    post:
      summary: Retrieve a document
      operationId: documentRetrieve
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandSchema'
      responses:
        '200':
          description: Document retrieved successfully
  /data/ingest:
    post:
      summary: Ingest data
      operationId: dataIngest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandSchema'
      responses:
        '200':
          description: Data ingested successfully
  /content/publish:
    post:
      summary: Publish content
      operationId: contentPublish
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandSchema'
      responses:
        '200':
          description: Content published successfully
  /email/send:
    post:
      summary: Send email
      operationId: emailSend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandSchema'
      responses:
        '200':
          description: Email sent successfully
  /ecommerce/interact:
    post:
      summary: Interact with e-commerce platform
      operationId: ecommerceInteract
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandSchema'
      responses:
        '200':
          description: E-commerce interaction successful
components:
  schemas:
    CommandSchema:
      type: object
      properties:
        command:
          type: string
        parameters:
          type: object
      required:
        - command
```
